package rs.ac.metropolitan.cs330_dz11_anteaprimorac5157.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF9C2AA1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFF96FC)
val md_theme_light_onPrimaryContainer = Color(0xFF57005C)
val md_theme_light_secondary = Color(0xFF97339A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDF74DE)
val md_theme_light_onSecondaryContainer = Color(0xFF210023)
val md_theme_light_tertiary = Color(0xFF824C74)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC78AB5)
val md_theme_light_onTertiaryContainer = Color(0xFF23001F)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFF7FA)
val md_theme_light_onBackground = Color(0xFF211920)
val md_theme_light_surface = Color(0xFFFFF7FA)
val md_theme_light_onSurface = Color(0xFF211920)
val md_theme_light_surfaceVariant = Color(0xFFF3DCEC)
val md_theme_light_onSurfaceVariant = Color(0xFF51424F)
val md_theme_light_outline = Color(0xFF847280)
val md_theme_light_inverseOnSurface = Color(0xFFFDECF7)
val md_theme_light_inverseSurface = Color(0xFF372D35)
val md_theme_light_inversePrimary = Color(0xFFFFA9FA)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF9C2AA1)
val md_theme_light_outlineVariant = Color(0xFFD6C0D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFC5F8)
val md_theme_dark_onPrimary = Color(0xFF5A005F)
val md_theme_dark_primaryContainer = Color(0xFFF980F8)
val md_theme_dark_onPrimaryContainer = Color(0xFF440048)
val md_theme_dark_secondary = Color(0xFFFFAAF9)
val md_theme_dark_onSecondary = Color(0xFF5A005F)
val md_theme_dark_secondaryContainer = Color(0xFFB14BB2)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_tertiary = Color(0xFFF4B2E0)
val md_theme_dark_onTertiary = Color(0xFF4E1F44)
val md_theme_dark_tertiaryContainer = Color(0xFF9B628C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191118)
val md_theme_dark_onBackground = Color(0xFFEEDEE8)
val md_theme_dark_surface = Color(0xFF191118)
val md_theme_dark_onSurface = Color(0xFFEEDEE8)
val md_theme_dark_surfaceVariant = Color(0xFF51424F)
val md_theme_dark_onSurfaceVariant = Color(0xFFD6C0D0)
val md_theme_dark_outline = Color(0xFF9E8B9A)
val md_theme_dark_inverseOnSurface = Color(0xFF372D35)
val md_theme_dark_inverseSurface = Color(0xFFEEDEE8)
val md_theme_dark_inversePrimary = Color(0xFF9C2AA1)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFC5F8)
val md_theme_dark_outlineVariant = Color(0xFF51424F)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF0079B2)